(ns kosmos.server-test
  (:require [clojure.test :refer :all]
            [clojure.java.jdbc :as jdbc]
            [kosmos :refer [start! stop! map->system system]]))

(def config {
             :server
             {
              :kosmos/init :kosmos.server/HsqlDbServerComponent
              :port        "9005"
              :database    "file:target/db/test"
              :dbname      "test"
              }

             :db
             {
              :classname       "org.hsqldb.jdbc.JDBCDriver"
              :subprotocol     "hsqldb"
              :protocol        "hsql"
              :subname         "hsql://localhost:9005/test"
              :host            "localhost"
              :port            9005
              :database        "test"
              :user            "SA"
              :password        ""
              }
             })

(defn setup-db-server [f]
  (start! (map->system config))
  (f)
  (stop!))

(use-fixtures :once setup-db-server)

(defn inserted? [returned]
  ((comp :id first) returned))

(deftest server-started
  (let [db (:db system)]
    (is (= [0] (jdbc/execute! db ["drop table test if exists"])))
    (is (= [0] (jdbc/execute! db [(str "create table test ("
                                       " id bigint generated by default as identity (start with 1001),"
                                       " name varchar(255) not null,"
                                       " description varchar(255),"
                                       " primary key (id)"
                                       " )")])))
    (is (inserted? (jdbc/insert! db :test {:name "test-01" :description "a test record one"})))
    (is (inserted? (jdbc/insert! db :test {:name "test-02" :description "a test record two"})))
    (is (inserted? (jdbc/insert! db :test {:name "test-03" :description "a test record three"})))
    (is (inserted? (jdbc/insert! db :test {:name "test-04" :description "a test record four"})))))


